# Generated by Django 4.1.7 on 2023-03-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cliente_carbohidratos_alter_cliente_proteinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='alergias',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_m',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_p',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='carbohidratos',
            field=models.CharField(blank=True, default='', max_length=700, verbose_name='Carbohidratos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Residencia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='enfermedades',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Enfermedades'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estatura',
            field=models.FloatField(blank=True, default=0, verbose_name='Estatura'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_actual',
            field=models.TextField(blank=True, default='', verbose_name='foto actual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hr_despertar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hr_dormir',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hr_entrenamiento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='peso',
            field=models.FloatField(blank=True, default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='proteinas',
            field=models.CharField(blank=True, default='', max_length=700, verbose_name='Proteinas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(blank=True, default=0, verbose_name='Teléfono'),
        ),
    ]
