# Generated by Django 4.1.1 on 2023-04-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_cliente_alergias_alter_cliente_apellido_m_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
