# Generated by Django 4.1.1 on 2023-04-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_cliente_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, max_length=10, verbose_name="Teléfono"),
        ),
    ]
