# Generated by Django 4.1.1 on 2023-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_cliente_telefono"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(verbose_name="imagen")),
                ("text", models.CharField(max_length=300, verbose_name="Texto")),
            ],
        ),
    ]
