# Generated by Django 4.1.1 on 2023-04-13 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_experiences"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experiences",
            old_name="user_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="experiences",
            old_name="opinion",
            new_name="text",
        ),
    ]
