# Generated by Django 4.1.9 on 2023-06-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_user_name_experiences_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pago',
            field=models.TextField(blank=True, default='', verbose_name='pago'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='image',
            field=models.TextField(default='xdxd', verbose_name='image body'),
        ),
    ]
