# Generated by Django 4.1.9 on 2023-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cliente_pago_alter_experiences_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dulces',
            field=models.CharField(default='', max_length=20),
        ),
    ]
