# Generated by Django 4.1.9 on 2023-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_cliente_dulces'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='accept_payment',
            field=models.BooleanField(default=False, verbose_name='aceptar pago'),
        ),
    ]
