# Generated by Django 4.1.9 on 2023-06-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cliente_accept_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='trainer_comments',
            field=models.CharField(default='', max_length=100, verbose_name='comentarios entrenador'),
        ),
    ]
