# Generated by Django 4.1.9 on 2023-07-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cliente_imagetraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=100, verbose_name='Dieta')),
                ('training', models.CharField(max_length=100, verbose_name='Entrenamiento')),
                ('drugs', models.CharField(max_length=100, verbose_name='Farmacologia')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='favorite_meal',
            field=models.CharField(default='', max_length=100, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='service',
            field=models.CharField(default='', max_length=100, verbose_name='Servicio'),
        ),
    ]
