# Generated by Django 4.1.9 on 2023-07-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_prices_diet_alter_prices_drugs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='diet',
            field=models.FloatField(verbose_name='Dieta'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='drugs',
            field=models.FloatField(verbose_name='Farmacologia'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='training',
            field=models.FloatField(verbose_name='Entrenamiento'),
        ),
    ]
