# Generated by Django 4.1.9 on 2023-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_prices_diet_alter_prices_drugs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='img_diet',
            field=models.TextField(default='', verbose_name='Dieta'),
        ),
    ]
