# Generated by Django 4.1.9 on 2023-07-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userbodyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_first_form',
            field=models.BooleanField(default=False),
        ),
    ]
