# Generated by Django 4.1.9 on 2023-07-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_cliente_is_first_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_first_form',
            field=models.BooleanField(default=True),
        ),
    ]
