# Generated by Django 4.1.9 on 2023-07-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_cliente_is_first_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatura', models.FloatField(blank=True, default=0, verbose_name='Estatura')),
                ('peso', models.FloatField(blank=True, default=0, verbose_name='Peso')),
                ('enfermedades', models.CharField(blank=True, default='', max_length=250, verbose_name='Enfermedades')),
                ('alergias', models.CharField(blank=True, default='', max_length=200, verbose_name='Alergias')),
                ('dulces', models.CharField(default='', max_length=20)),
                ('hr_entrenamiento', models.CharField(blank=True, max_length=10)),
                ('hr_despertar', models.CharField(blank=True, max_length=10)),
                ('foto_actual', models.TextField(blank=True, default='', verbose_name='foto actual')),
                ('pago', models.TextField(blank=True, default='', verbose_name='pago')),
                ('hr_dormir', models.CharField(blank=True, max_length=20)),
                ('proteinas', models.CharField(blank=True, default='', max_length=700, verbose_name='Proteinas')),
                ('carbohidratos', models.CharField(blank=True, default='', max_length=700, verbose_name='Carbohidratos')),
                ('objetivo', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Objetivo(s)')),
                ('service', models.CharField(default='', max_length=100, verbose_name='Servicio')),
                ('favorite_meal', models.CharField(default='', max_length=100, verbose_name='')),
            ],
        ),
    ]
