# Generated by Django 4.1.9 on 2023-07-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_trackform'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackform',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
