# Generated by Django 4.1.9 on 2023-07-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_trackform_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackform',
            name='foto_actual',
        ),
    ]
