# Generated by Django 4.1.9 on 2023-07-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_trackform_foto_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackform',
            name='foto_actual',
            field=models.TextField(default=''),
        ),
    ]
